name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  train:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Set up Python 3.6 environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/training.txt
    
    # Create the model
    - name: Create the model
      run: |
        python src/training/train.py

    # Upload model
    - name: Upload model as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: src/training/model.pickle


  build:
    needs: train
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Download model
    - name: Download model from training job
      uses: actions/download-artifact@v2
      with:
        name: model
        path: src/training/

    # Set up Python 3.6 environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/inference.txt
        pip install pytest

    # Run our unit tests
    - name: Run unit tests
      run: |
        python -m pytest
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: axelsalamartin/demo-flask-app
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}